### ISSUE TITLE
Suggestion for adjustment to auto research.

### ISSUE THREAD

**Issue by erkle64** [shiggityshaggs/FoundryClientMods#2]
Can't live without you ResearchQueue mod.  It's so handy.  I've been using a modified version because it sometimes gets stuck trying to research a tier 3 research before it's finished all the tier 2 researches and I haven't automated tier 3.
There's probably a better way of doing it, but I've been using this code.
```cs
    var lowestTier = int.MaxValue;
    ResearchTemplate lowestTierResearch = null;
    foreach (var kvp in ResearchSystem.getAvailableResearchTemplateDictionary())
    {
        if ((BuildInfo.isDemo && !kvp.Value.includeInDemo) || kvp.Value.isLockedByMissingEntitlement()) continue;
        var tier = kvp.Value.input_data.Length;
        if (tier < lowestTier)
        {
            lowestTier = tier;
            lowestTierResearch = kvp.Value;
        }
    }
    if (lowestTierResearch != null)
    {
        GameRoot.addLockstepEvent(new StartResearchEvent(lowestTierResearch.id, false));
    }
```

**Comment by shiggityshaggs** [comment]
Good point, thanks for the input! It should now finish up a tier before progressing with the next one.
On testbranch, at least. I'll push to main soon™
